### ISSUE TITLE
Data Model Integrity

### ISSUE THREAD

**Issue by alex-nexus** [slvdrog/play-my-tune-api#1]
Please consider the cases for handling both data model and API,  
1. What happens when deleting a song that's part of a playlist?
2. What happens when deleting an album with songs?
3. What happens when deleting a playlist with songs?

**Comment by slvdrog** [comment]
1. When a song that is part of a playlist is deleted, the song gets removed from the PlaylistSongs table thus removing it from the playlist.

2. Deleting an album deletes every song associated to it.

3. I was missing a dependent: :destroy on the relation between playlists and playlists_songs. Now when a playlist gets deleted, every PlaylistSong for that one gets removed, but the Song still exists. Added the fix on the created PR.

**Comment by slvdrog** [comment]
PR: https://github.com/slvdrog/play-my-tune-api/pull/4
