### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by alex-nexus** [slvdrog/play-my-tune-api#2]
What are the APIs you would do performance tuning? 
What if album or playlist GET SHOW APIs need to return songs?

**Comment by slvdrog** [comment]
I've created a PR that implements caching on GET INDEX and GET SHOW actions and adds the songs inheritance to the responses.
These are the endpoints that benefit the most from caching, as the responses will get bigger and bigger as the database grows, and those are the actions most likely to be hit the most.

**Comment by slvdrog** [comment]
PR: https://github.com/slvdrog/play-my-tune-api/pull/4

**Comment by alex-nexus** [comment]
ok
